force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SiteVisit-{0000}</displayFormat>
        <label>Site Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <formula>TEXT( SLead__r.Lead_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/SLead__c.field-meta.xml
<CustomField>
    <fullName>SLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <label>Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Verified by GRE</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Not Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/pushToSalesControllerTest.cls
@istest
public class pushToSalesControllerTest {
 @isTest
    public static void method() {
      
          Lead lad= new Lead();
        lad.LastName='test';
        lad.Allocated_Project__c = 'Zuari Garden City';
        lad.Phone = '9182748514';
        lad.Source_Type__c='Digital Marketing';
        lad.Lead_source__c = 'Facebook';
        lad.Lead_Status__c ='New';
        lad.OwnerId = UserInfo.getUserId();
        lad.Lead_Assigned__c = false;
        lad.IsPushed__c = true;
        lad.Company='test';
        insert lad;
		
        Site_Visit__c sv=new Site_Visit__c();  
        sv.Date__c=System.now()+3;
        sv.Status__c='Scheduled';
        sv.Project__c='Zuari Garden City';
        sv.SLead__c=lad.id;
        insert sv;
        Test.startTest();
        pushToSalesController.moveToSales(lad.Id, 'hgbvui');
        pushToSalesController.isSiteVisitScheduled(lad.Id);
        pushToSalesController.CheckFollowups(lad.Id);
        Test.stopTest();
    }
}