force-app/main/default/objects/Plot__c/Plot__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot__c/fields/Holding_Time__c.field-meta.xml
<CustomField>
    <fullName>Holding_Time__c</fullName>
    <label>Holding Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Plot_Type__c.field-meta.xml
<CustomField>
    <fullName>Plot_Type__c</fullName>
    <label>Plot Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intermediate Site</fullName>
            </value>
            <value>
                <fullName>Corner Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>to capture the availability of the plot</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>BLOCKED</fullName>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/TAT_for_Holding_Unit__c.field-meta.xml
<CustomField>
    <fullName>TAT_for_Holding_Unit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>TAT for Holding Unit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{0000}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Plot_Type__c.field-meta.xml
<CustomField>
    <fullName>Plot_Type__c</fullName>
    <label>Plot Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intermediate Site</fullName>
            </value>
            <value>
                <fullName>Corner Site</fullName>
            </value>
            <value>
                <fullName>Nirvana</fullName>
                <isActive>false</isActive>
                <label>Nirvana</label>
            </value>
            <value>
                <fullName>Zion</fullName>
                <isActive>false</isActive>
                <label>Zion</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_status__c.field-meta.xml
<CustomField>
    <fullName>Quote_status__c</fullName>
    <label>Quote status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drafted</fullName>
                <default>true</default>
                <label>Drafted</label>
            </value>
            <value>
                <fullName>submitted for approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>sent to customer</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Plot__c.Project_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>Plot__c.Status__c</field>
            <operation>equals</operation>
            <value>Vacant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plot__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/recordTypes/Plots.recordType-meta.xml
<RecordType>
    <fullName>Plots</fullName>
    <active>true</active>
    <label>Plots</label>
</RecordType>

force-app/main/default/classes/QuotePdfController.cls
public without sharing class QuotePdfController {
    @AuraEnabled
    public static string sendEmailtoCustomer(String recId)
    {
        Quote__c qt = [SELECT Id,payment_type__c,Quote_status__c,Approval_status__c, Project__c, SLead__r.Email, SLead__r.Secondary_Email__c,Plot_Type__c,SLead__c ,RecordType.DeveloperName  FROM Quote__c WHERE Id=:recId];
    //    if(qt.Quote_status__c == 'Approved' || qt.Quote_status__c == 'Drafted'){
            Messaging.SingleEmailMessage semail = new Messaging.SingleEmailMessage();
            Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
            PageReference pref;
            
            if(qt.RecordType.DeveloperName=='Plots'){
                pref= page.CostSheet;
                
            }else{
                pref= page.ZuariCostSheet;
            }
            
            //pref=page.EIPL;
            pref.getParameters().put('id',recId);
            pref.setRedirect(true);
            system.debug(pref);
            Blob b;
            
            Boolean isTest = System.Test.isRunningTest();
            if(isTest){
                b = blob.valueOf('Unit.Test');
            }else{
                b = pref.getContent();
            }
            attach.setFileName('Zuari_CostSheet.pdf');
            attach.setBody(b);
            semail.setSubject('Zuari Cost Sheet');
            system.debug(qt.SLead__r.Email);
            List<string> sendTo = new List<string>();
            if(qt.SLead__r.Email !=null){
                sendTo.add(qt.SLead__r.Email);
            }
            
            if(qt.SLead__r.Secondary_Email__c !=null){
                sendTo.add(qt.SLead__r.Secondary_Email__c);
            }
            
            semail.setToAddresses(sendTo);
            semail.setHtmlBody('Dear Sir/Madam,<br/> <br/> Thank you very much for your interest in '+qt.Project__c +'.<br/>Please find the attached quote for your kind Perusal.<br/>Note: This is a sample quote purely for reference.<br/>Please feel free to talk us for clarification if any.,<br/>');
            semail.setFileAttachments(new Messaging.EmailFileAttachment[]{attach});
            if(sendTo.size()>0){
                Messaging.sendEmail(new Messaging.SingleEmailMessage[]{semail});
                system.debug(semail);
                
                Quote__c q = [select Id, Name, Quote_status__c from Quote__c where id = :recId limit 1];
                q.Quote_status__c = 'sent to customer';
                update q;
                return 'Quotation sent to customer';
            }else{
                return 'Please enter email address in lead';
            }
     //  }else{
           // return 'Quote is not approved, you can not send Quote';
      //  }
    }
    /*@AuraEnabled*/
    /*public static void callUnitHoldController(String recId){
        Quote__c qt = [SELECT Id,Quote_status__c,Unit__c, Project__c,Unit__r.Project__c, Unit__r.Project__r.TAT_for_Holding_Unit__c   FROM Quote__c WHERE Id=:recId];
        
        plot__c pt=new plot__c();
        pt.id = qt.Unit__c;
        System.debug('samp2'+pt.Id);
        pt.Status__c='Hold';
        qt.Quote_status__c = 'Hold';
		update new List<SObject>{ pt, qt };
        DateTime dt = System.now(); 
        if(qt.Unit__r.Project__r.TAT_for_Holding_Unit__c>0){
            
        Decimal tat = qt.Unit__r.Project__r.TAT_for_Holding_Unit__c;
        DateTime newDateTime = dt.addMinutes(Integer.ValueOf(tat)); 
        
        if(newDateTime!=null && newDateTime> system.now()){
            system.debug(newDateTime);
            pt.Holding_Time__c= newDateTime ;  
        }
        
        if(pt.Id!=null){
            update pt;
        }
        }
    } */
    
    
}