force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_up__c/Follow_up__c.object-meta.xml
<CustomObject>
    <label>Follow up</label>
    <nameField>
        <displayFormat>F-{000}</displayFormat>
        <label>Follow up Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_up__c/fields/Related_Source__c.field-meta.xml
<CustomField>
    <fullName>Related_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Source</label>
    <referenceTo>Related_Source__c</referenceTo>
    <relationshipLabel>Follow ups</relationshipLabel>
    <relationshipName>Follow_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>NT-{0000}</displayFormat>
        <label>Notification Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/IsNotificationSent__c.field-meta.xml
<CustomField>
    <fullName>IsNotificationSent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsNotificationSent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Notification_Category__c.field-meta.xml
<CustomField>
    <fullName>Notification_Category__c</fullName>
    <label>Notification Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offers</fullName>
            </value>
            <value>
                <fullName>New Launch</fullName>
            </value>
            <value>
                <fullName>User Specific</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Notification_Content__c.field-meta.xml
<CustomField>
    <fullName>Notification_Content__c</fullName>
    <label>Notification Content</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Notification_Heading__c.field-meta.xml
<CustomField>
    <fullName>Notification_Heading__c</fullName>
    <label>Notification_Heading</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Notification_Type__c.field-meta.xml
<CustomField>
    <fullName>Notification_Type__c</fullName>
    <label>Notification Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead Notification</fullName>
            </value>
            <value>
                <fullName>Followup Notification</fullName>
            </value>
            <value>
                <fullName>Site Visit Notification</fullName>
            </value>
            <value>
                <fullName>Payment Notification</fullName>
            </value>
            <value>
                <fullName>Announcement Notification</fullName>
            </value>
            <value>
                <fullName>Reward and Top performed CPs Notification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Line_Item__c/Payment_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Line Item</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Line_Item__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Payment Line Items</relationshipLabel>
    <relationshipName>Payment_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Line_Item__c/fields/Payament_Status__c.field-meta.xml
<CustomField>
    <fullName>Payament_Status__c</fullName>
    <label>Payament Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Line_Item__c/fields/Payment_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Payment_Line_Item__c</fullName>
    <displayFormat>PLI-{000}</displayFormat>
    <label>Payment Line Item</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Related_Source__c/Related_Source__c.object-meta.xml
<CustomObject>
    <label>Related Source</label>
    <nameField>
        <displayFormat>RS-{000}</displayFormat>
        <label>Related Source</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Sources</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Source__c/fields/Channel_Partner1__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Related Sources (Channel Partner)</relationshipLabel>
    <relationshipName>Related_Sources1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Source__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Sources</relationshipLabel>
    <relationshipName>Related_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Source__c/fields/Lead_status1__c.field-meta.xml
<CustomField>
    <fullName>Lead_status1__c</fullName>
    <label>Lead status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>RNR</fullName>
            </value>
            <value>
                <fullName>Pre Sales Follow Up</fullName>
            </value>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Site Visit Schedule</fullName>
            </value>
            <value>
                <fullName>New sales enquiry</fullName>
            </value>
            <value>
                <fullName>Sales Follow up</fullName>
            </value>
            <value>
                <fullName>SV Completed</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Request for Rejection</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SiteVisit-{0000}</displayFormat>
        <label>Site Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Related_Source__c.field-meta.xml
<CustomField>
    <fullName>Related_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Source</label>
    <referenceTo>Related_Source__c</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Verified by GRE</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Not Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NotificationHandler.cls
public with sharing class NotificationHandler {
   /**
 * @description
 * Handler class responsible for creating Notification__c records
 *
 * This class is invoked from the RelatedSourceTrigger,FollowUpTrigger,SiteVisitTrigger and PaymentTrigger during the
 * after update context and detects status field changes
 * to initiate notification creation.
 *
 *
 * @usage
 * Called from RelatedSourceTrigger (after update context).
 * Called from SiteVisitTrigger (after update context).
 * Called from FollowUpTrigger (after update context).
 * Called from PaymentTrigger (after update context).
 *
 * @author
 * Praveen Kumar
 *
 */
    public static void createNotificationRecordsForRelatedSource(List<Related_Source__c> newList,  Map<Id, Related_Source__c> oldMap) {
    Map<Id, Notification__c> existingNotifications = new Map<Id, Notification__c>();

    // Fetch existing notifications
    for (Notification__c n :[SELECT Id, Related_Source__c
         					FROM Notification__c
         					WHERE Related_Source__c IN :newList
         					AND Notification_Category__c = 'User Specific'
         					AND IsActive__c = true]) {
        existingNotifications.put(n.Related_Source__c, n);
    }

    List<Notification__c> toInsert = new List<Notification__c>();
    List<Notification__c> toUpdate = new List<Notification__c>();

    for (Related_Source__c newRec : newList) {
        Related_Source__c oldRec = oldMap.get(newRec.Id);

        if (newRec.Lead_status1__c != oldRec.Lead_status1__c &&
            newRec.Channel_Partner1__c != null) {

            Notification__c noti;

            if (existingNotifications.containsKey(newRec.Id)) {
               
                noti = existingNotifications.get(newRec.Id);
            } else {
                // CREATE
                noti = new Notification__c();
                noti.Related_Source__c = newRec.Id;
                noti.Notification_Category__c = 'User Specific';
                noti.IsActive__c = true;
                noti.IsNotificationSent__c = false;
                toInsert.add(noti);
            }

            // Common field updates
            noti.Updated_Status__c = newRec.Lead_status1__c;
            noti.Notification_Type__c = 'Lead Notification';
            noti.Notification_Heading__c = 'Lead Status Changed';
            noti.Notification_Content__c = 'Status has been updated by this Lead Owner';
            noti.Channel_Partner__c = newRec.Channel_Partner1__c;
            noti.Notification_Redirect_Id__c = newRec.Lead_Id__c;

            if (noti.Id != null) {
                toUpdate.add(noti);
            }
        }
    }

    if (!toInsert.isEmpty()) insert toInsert;
    if (!toUpdate.isEmpty()) update toUpdate;
}


public static void createNotificationRecordsForSiteVisit(List<Site_Visit__c> newList, Map<Id, Site_Visit__c> oldMap  ) {
        List<Notification__c> notificationsToInsert = new List<Notification__c>();
    for (Site_Visit__c newRec : newList) {

        Site_Visit__c oldRec = oldMap.get(newRec.Id);

        // ✅ Condition 1: Visit Status changed
        Boolean isStatusChanged = newRec.Status__c != oldRec.Status__c;

        // ✅ Condition 2: Channel Partner exists
        Boolean hasChannelPartner = newRec.Channel_Partner1__c != null;
        if (isStatusChanged && hasChannelPartner) {

            Notification__c noti = new Notification__c();
            noti.Site_Visit__c = newRec.Id;
            
            noti.Updated_Status__c = newRec.Status__c;
            noti.Notification_Type__c = 'Site Visit Notification';
            noti.Notification_Heading__c = 'Site Visit Status Changed';
            noti.Notification_Content__c = 'Status has been updated by Site Visit Owner';
            noti.IsActive__c = true;
            noti.Channel_Partner__c = newRec.Channel_Partner1__c;
            noti.Notification_Redirect_Id__c= newRec.Name;
            noti.IsNotificationSent__c = false;
            noti.Notification_Category__c='User Specific';

            notificationsToInsert.add(noti);
        }
}
    
    if (!notificationsToInsert.isEmpty()) {
        insert notificationsToInsert;
    }
}
    public static void createNotificationRecordsForFollowUp(List<Follow_up__c> newList, Map<Id, Follow_up__c> oldMap  ) {
        List<Notification__c> notificationsToInsert = new List<Notification__c>();
    for (Follow_up__c newRec : newList) {

        Follow_up__c oldRec = oldMap.get(newRec.Id);

        // ✅ Condition 1: Follow Up Status changed
        Boolean isStatusChanged = newRec.Status__c != oldRec.Status__c;

        // ✅ Condition 2: Channel Partner exists
        Boolean hasChannelPartner = newRec.Channel_Partner__c != null;
        if (isStatusChanged && hasChannelPartner) {

            Notification__c noti = new Notification__c();
            noti.Follow_up__c = newRec.Id;
            
            noti.Updated_Status__c = newRec.Status__c;
                noti.Notification_Type__c = 'Followup Notification';
            noti.Notification_Heading__c = 'Follow Up Status Changed';
            noti.Notification_Content__c = 'Status has been updated by Follow Up Owner';
            noti.IsActive__c = true;
            noti.Channel_Partner__c = newRec.Channel_Partner__c;
            noti.Notification_Redirect_Id__c= newRec.Name;
            noti.IsNotificationSent__c = false;
            noti.Notification_Category__c='User Specific';

            notificationsToInsert.add(noti);
        }
    }
    if (!notificationsToInsert.isEmpty()) {
        insert notificationsToInsert;
    }
    }
    public static void createNotificationRecordsForPayment(List<Payment_Line_Item__c> newList, Map<Id, Payment_Line_Item__c> oldMap  ) {
        List<Notification__c> notificationsToInsert = new List<Notification__c>();
    for (Payment_Line_Item__c newRec : newList) {

        Payment_Line_Item__c oldRec = oldMap.get(newRec.Id);

        // ✅ Condition 1: Payment Status changed
        Boolean isStatusChanged = newRec.Payament_Status__c != oldRec.Payament_Status__c;

        // ✅ Condition 2: Channel Partner exists
        Boolean hasChannelPartner = newRec.Channel_Partner__c != null;
        if (isStatusChanged && hasChannelPartner) {

            Notification__c noti = new Notification__c();
            noti.Payment_Line_Item__c = newRec.Id;
            
            noti.Updated_Status__c = newRec.Payament_Status__c;
            noti.Notification_Type__c = 'Payment Notification';
            noti.Notification_Heading__c = 'Payment Status Changed';
            noti.Notification_Content__c = 'Status has been updated by Payment Owner';
            noti.IsActive__c = true;
            noti.Channel_Partner__c = newRec.Channel_Partner__c;
            noti.Notification_Redirect_Id__c= newRec.Payment_Line_Item__c;
            noti.IsNotificationSent__c = false;
            noti.Notification_Category__c='User Specific';

            notificationsToInsert.add(noti);
        }
    }
    if (!notificationsToInsert.isEmpty()) {
        insert notificationsToInsert;
    }
}
}