force-app/main/default/objects/Round_Robin__c/Round_Robin__c.object-meta.xml
<CustomObject>
    <label>Round Robin</label>
    <nameField>
        <displayFormat>RR{00}</displayFormat>
        <label>Round Robin Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robins</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin_Member__c/Round_Robin_Member__c.object-meta.xml
<CustomObject>
    <label>Round Robin Member</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Round Robin Members Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin_Member__c/fields/Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round Robin</label>
    <referenceTo>Round_Robin__c</referenceTo>
    <relationshipLabel>Round Robin Members</relationshipLabel>
    <relationshipName>Round_Robin_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RoundRobinUsersViewTest.cls
@isTest
public class RoundRobinUsersViewTest {

    @isTest
    Public static void testRoundRobinMethods() {
        Round_Robin__c testRoundRobin = new Round_Robin__c();
        insert testRoundRobin;
        
        List<Round_Robin_Member__c> testMembers = new List<Round_Robin_Member__c>();
        for(Integer i = 0; i < 2; i++) {
            testMembers.add(new Round_Robin_Member__c(
                Round_Robin__c = testRoundRobin.Id,
                Active__c = true
            ));
        }
        insert testMembers;
        
        List<Round_Robin_Member__c> result1 = RoundRobinUsersView.fetchRoundRobinMembers(testRoundRobin.Id);
        
        for(Round_Robin_Member__c member : result1) {
            System.assertEquals(true, member.Active__c, 'Round Robin Member should be active');
        }
        
        Round_Robin_Member__c testMember = testMembers[0];
        List<Round_Robin_Member__c> updatedMembers;
        
        updatedMembers = RoundRobinUsersView.toggleMemberStatus(testMember.Id, testRoundRobin.Id);
        Round_Robin_Member__c updatedMember = updatedMembers[0];
        
        updatedMembers = RoundRobinUsersView.toggleMemberStatus(testMember.Id, testRoundRobin.Id);
        updatedMember = updatedMembers[0];
    }
}