force-app/main/default/objects/Round_Robin__c/Round_Robin__c.object-meta.xml
<CustomObject>
    <label>Round Robin</label>
    <nameField>
        <displayFormat>RR{00}</displayFormat>
        <label>Round Robin Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robins</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin_Member__c/Round_Robin_Member__c.object-meta.xml
<CustomObject>
    <label>Round Robin Member</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Round Robin Members Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin_Member__c/fields/Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round Robin</label>
    <referenceTo>Round_Robin__c</referenceTo>
    <relationshipLabel>Round Robin Members</relationshipLabel>
    <relationshipName>Round_Robin_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Round_Robin_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Member__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Sales</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Pre Sales Head</fullName>
            </value>
            <value>
                <fullName>Sales Head</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RoundRobinUsersView.cls
public without sharing class  RoundRobinUsersView {
     @AuraEnabled(cacheable=true)
    public static List<Round_Robin_Member__c> fetchRoundRobinMembers(string recordId) {
        return [SELECT Id, Name, Active__c,User__r.Name,User_Type__c FROM Round_Robin_Member__c where Round_Robin__c=:recordId ];
    }
    

    @AuraEnabled
    public static List<Round_Robin_Member__c> toggleMemberStatus(Id memId,string recId) {
        Round_Robin_Member__c member = [SELECT Id, Active__c,User__r.Name,User_Type__c FROM Round_Robin_Member__c WHERE Id = :memId LIMIT 1];
        member.Active__c = !member.Active__c;
        update member;

		return [SELECT Id, Name, Active__c,User__r.Name,User_Type__c FROM Round_Robin_Member__c where Round_Robin__c=:recId];
    }

}