force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Invoice_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Line Item</label>
    <referenceTo>Invoice_Line_Item__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <label>GST</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Agreement_Amount__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Amount__c</fullName>
    <label>Agreement Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Cancelled_Booking_Amount__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_Booking_Amount__c</fullName>
    <label>Cancelled Booking Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Commsison_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Commsison_Percentage__c</fullName>
    <defaultValue>6</defaultValue>
    <label>Commsison Percentage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <defaultValue>6</defaultValue>
    <label>GST</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Net_Investment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Net_Investment_Amount__c</fullName>
    <label>Net Investment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Net_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Net_Invoice_Amount__c</fullName>
    <label>Net Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Project_Name1__c.field-meta.xml
<CustomField>
    <fullName>Project_Name1__c</fullName>
    <label>Project Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Name</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>38</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TDS__c.field-meta.xml
<CustomField>
    <fullName>TDS__c</fullName>
    <label>TDS</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{00000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <label>Agreement Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Invoice Line Item</relationshipLabel>
    <relationshipName>Invoice_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Cancelled_Booking_Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_Booking_Commission_Amount__c</fullName>
    <label>Cancelled Booking Commission Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commission_Amount__c</fullName>
    <label>Commission Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Item</relationshipLabel>
    <relationshipName>Invoice_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Name</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Payment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Processed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Processed_Amount__c</fullName>
    <label>Processed Amount</label>
    <summarizedField>Payment_Line_Item__c.Booking_Amount__c</summarizedField>
    <summaryForeignKey>Payment_Line_Item__c.Payment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_Line_Item__c/Payment_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Line Item</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Line Items</relationshipLabel>
    <relationshipName>Payment_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Line_Item__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Payment Line Items</relationshipLabel>
    <relationshipName>Payment_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Line_Item__c/fields/Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commission_Amount__c</fullName>
    <label>Commission Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Payment Line Items</relationshipLabel>
    <relationshipName>Payment_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Line_Item__c/fields/Invoice_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Line Item</label>
    <referenceTo>Invoice_Line_Item__c</referenceTo>
    <relationshipLabel>Payment Line Items</relationshipLabel>
    <relationshipName>Payment_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Line_Item__c/fields/Payament_Status__c.field-meta.xml
<CustomField>
    <fullName>Payament_Status__c</fullName>
    <label>Payament Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Line_Item__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payment Line Items</relationshipLabel>
    <relationshipName>Payment_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Line_Item__c/fields/Payment_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Payment_Line_Item__c</fullName>
    <displayFormat>PLI-{000}</displayFormat>
    <label>Payment Line Item</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Payment_Line_Item__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <length>38</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Line_Item__c/fields/Processing_date__c.field-meta.xml
<CustomField>
    <fullName>Processing_date__c</fullName>
    <label>Processing date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Line_Item__c/fields/Project_name__c.field-meta.xml
<CustomField>
    <fullName>Project_name__c</fullName>
    <label>Project Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Name</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Line_Item__c/fields/Transcantion_Number__c.field-meta.xml
<CustomField>
    <fullName>Transcantion_Number__c</fullName>
    <label>Transcantion Number</label>
    <length>38</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ChannelPartnerPaymentController.cls
public with sharing class ChannelPartnerPaymentController {

    @AuraEnabled(cacheable=true)
    public static List<Invoice__c> getInvoices(Id recId) {
        
        if (recId == null) {
            throw new AuraHandledException('Channel Partner Id is required');
        }
        
        return [
            SELECT Id,Name,Agreement_Amount__c,Commission_Amount__c,Cancelled_Booking_Amount__c, TDS__c,GST__c,Channel_Partner__c,Net_Invoice_Amount__c,Invoice_Date__c,
            Project_Name1__c,
            Invoice_Status__c,
            Commsison_Percentage__c,
            Net_Investment_Amount__c
            FROM Invoice__c
            WHERE Channel_Partner__c = :recId AND Invoice_Status__c = 'Pending' ORDER BY CreatedDate DESC
        ];
    }

    /* Create Payment + Line Items */
    /* Create Payment + Line Items */
   @AuraEnabled
public static Id createPayment(
    String baseName,
    Date paymentDate,
    String utrNumber,
    String status,
    String paymentMethod,
    List<Id> invoiceIds,
    Id recId
) {
    System.debug('=== createPayment START ===');

    if (invoiceIds == null || invoiceIds.isEmpty()) {
        throw new AuraHandledException('No invoices selected');
    }

    /* ================= CREATE PAYMENT ================= */
    Payment__c payment = new Payment__c(
        Channel_Partner__c = recId,
        Payment_Status__c  = status
    );
    insert payment;

    /* ================= FETCH INVOICE LINE ITEMS ================= */
    List<Invoice_Line_Item__c> invoiceLineItems = [
        SELECT Id,Invoice__c, Invoice_Date__c, Project_Name__c, Commission_Amount__c, Cancelled_Booking_Commission_Amount__c, Agreement_Value__c, Booking__c
        FROM Invoice_Line_Item__c
        WHERE Invoice__c IN :invoiceIds
    ];

    if (invoiceLineItems.isEmpty()) {
        throw new AuraHandledException('No Invoice Line Items found');
    }

    List<Payment_Line_Item__c> paymentLineItems = new List<Payment_Line_Item__c>();
    Decimal totalAmount = 0;

    /* ================= CREATE PAYMENT LINE ITEMS ================= */
    Integer count = 1;
    for (Invoice_Line_Item__c ili : invoiceLineItems) {

        paymentLineItems.add(new Payment_Line_Item__c(
             Name                    = baseName + ' - ' + count,
            Payment__c              = payment.Id,
            Invoice_Line_Item__c    = ili.Id,          
            Payment_Method__c       = paymentMethod,
            Channel_Partner__c      = recId,
            Project_name__c         = ili.Project_Name__c,
            Processing_date__c      = Date.today(),
            Booking__c              = ili.Booking__c,
            Invoice__c              = ili.invoice__c,
            Payament_Status__c      = status,
            Transcantion_Number__c  = utrNumber,
            Commission_Amount__c       = ili.Commission_Amount__c
        ));
         count++;
    }

    insert paymentLineItems;

    /* ================= OPTIONAL TOTAL UPDATE ================= */
    // payment.Processed_Amount__c = totalAmount;
    // update payment;

    System.debug('=== createPayment END ===');

    return payment.Id;
}

}