force-app/main/default/objects/Follow_up__c/Follow_up__c.object-meta.xml
<CustomObject>
    <label>Follow up</label>
    <nameField>
        <displayFormat>F-{000}</displayFormat>
        <label>Follow up Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_up__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/SLead__c.field-meta.xml
<CustomField>
    <fullName>SLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Follow ups</relationshipLabel>
    <relationshipName>Follow_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/followUpControllerTest.cls
@isTest
public class followUpControllerTest {
    
    public static testMethod void getFollowUpDetailstest()
    {
        
        Lead lead=new Lead();
        lead.Lastname = 'Test Lead';
        lead.Company = 'TestCompany';
        lead.Phone__c = '9090909090';
        lead.Secondary_Phone__c = '9898989898';
        lead.Email = 'standarduser@testorgfil.com';
        insert lead;
        //follow_up__c fu = new follow_up__c();
        //fu.SLead__c = lead.Id;
        //fu.Status__c = 'Scheduled';
        //datetime dt = system.now();
        //fu.Scheduled_Date__c = dt.addMinutes(5);
        //insert fu;
        //System.debug(followUpController.getFollowUpDetails(lead.id));
        System.debug(followUpController.dateFormat('16/09/2023, 18:00:00'));
    }
}