force-app/main/default/objects/Follow_up__c/Follow_up__c.object-meta.xml
<CustomObject>
    <label>Follow up</label>
    <nameField>
        <displayFormat>F-{000}</displayFormat>
        <label>Follow up Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_up__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/SLead__c.field-meta.xml
<CustomField>
    <fullName>SLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Follow ups</relationshipLabel>
    <relationshipName>Follow_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/followUpController.cls
public class followUpController {
    
    @AuraEnabled
public static List<Follow_Up__c> getFollowUpDetails(Id leadId) {
    return [SELECT Scheduled_Date__c, Status__c FROM Follow_Up__c WHERE SLead__c = :leadId AND Status__c = 'Scheduled' ORDER BY CreatedDate DESC LIMIT 1 ];
}

    
    public static String dateFormat(String followupdate)
    { 	String dateTimeFormatted='';	
     String formattedDate='';
     String[] splitDateTime=followupdate.split(',');
     String[] splitDate=splitDateTime[0].split('/');
     for(integer i=splitDate.size()-1;i>=0;i--)
     {
         formattedDate+=splitDate[i];
         if(i!=0)
             formattedDate+='-';
     }
     
     dateTimeFormatted=	formattedDate+' '+splitDateTime[1];
     
     return dateTimeFormatted;
    }
}