force-app/main/default/objects/Follow_up__c/Follow_up__c.object-meta.xml
<CustomObject>
    <label>Follow up</label>
    <nameField>
        <displayFormat>F-{000}</displayFormat>
        <label>Follow up Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_up__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/SLead__c.field-meta.xml
<CustomField>
    <fullName>SLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Follow ups</relationshipLabel>
    <relationshipName>Follow_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SiteVisit-{0000}</displayFormat>
        <label>Site Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Revisit_Count__c.field-meta.xml
<CustomField>
    <fullName>Revisit_Count__c</fullName>
    <label>Revisit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/SLead__c.field-meta.xml
<CustomField>
    <fullName>SLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Verified by GRE</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Not Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReVisitControllerTest.cls
@isTest
public class ReVisitControllerTest {
      public static testMethod void getFollowUpDetailstest()
    {
        
        Lead lead=new Lead();
        lead.Lastname = 'Test Lead';
        lead.Company = 'TestCompany';
        lead.Phone__c = '9090909090';
        lead.Secondary_Phone__c = '9898989898';
        lead.Email = 'standarduser@testorgfil.com';
        insert lead;
        
        Site_Visit__c sv=new Site_Visit__c();  
        sv.Date__c=System.now()+3;
        sv.Status__c='Scheduled';
        sv.Project__c='Zuari Garden City';
        sv.SLead__c=lead.id;
        sv.Revisit_Count__c=0;
        sv.Reschedule_Date__c=System.now()+3;
        insert sv;
        //follow_up__c fu = new follow_up__c();
        //fu.SLead__c = lead.Id;
        //fu.Status__c = 'Scheduled';
        //datetime dt = system.now();
        //fu.Scheduled_Date__c = dt.addMinutes(5);
        //insert fu;
        ReVisitController.updateLastNote(sv.id,'test', system.now());
       }


}