force-app/main/default/objects/Follow_up__c/Follow_up__c.object-meta.xml
<CustomObject>
    <label>Follow up</label>
    <nameField>
        <displayFormat>F-{000}</displayFormat>
        <label>Follow up Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_up__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/SLead__c.field-meta.xml
<CustomField>
    <fullName>SLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Follow ups</relationshipLabel>
    <relationshipName>Follow_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Unqualification__c/Lead_Unqualification__c.object-meta.xml
<CustomObject>
    <label>Lead Unqualification</label>
    <nameField>
        <displayFormat>LU-{0000}</displayFormat>
        <label>Lead Unqualification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Unqualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Unqualification__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Unqualifications</relationshipLabel>
    <relationshipName>Lead_Unqualifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Unqualification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Sales</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Unqualification__c/fields/Unqualified_At__c.field-meta.xml
<CustomField>
    <fullName>Unqualified_At__c</fullName>
    <label>Unqualified At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead_Unqualification__c/fields/Unqualified_Reason__c.field-meta.xml
<CustomField>
    <fullName>Unqualified_Reason__c</fullName>
    <label>Unqualified Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Unqualification__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unqualified By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Lead_Unqualifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SiteVisit-{0000}</displayFormat>
        <label>Site Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <formula>TEXT( SLead__r.Lead_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/SLead__c.field-meta.xml
<CustomField>
    <fullName>SLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Verified by GRE</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Not Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadStatusController.cls
public with sharing class LeadStatusController {
    
    public static Boolean markleadUnqualified=false;
    
    public class dataWrapper{
        @AuraEnabled
        public string profileName{get;set;}
        @AuraEnabled
        public string recordTypeName{get;set;}
    }
    
    @AuraEnabled
    public static dataWrapper getLeadRecordTypeName(Id leadId) {
        dataWrapper dw = new dataWrapper();
        Lead lead = [SELECT RecordType.Name,Lead_Record_Type__c FROM Lead WHERE Id = :leadId LIMIT 1];
        Id profileId = UserInfo.getProfileId();
        
        Profile userProfile = [SELECT Id, Name FROM Profile WHERE Id = :profileId];
        dw.profileName = userProfile.Name;
        dw.recordTypeName = lead.RecordType.Name;
        return dw;
    }
    
    @AuraEnabled
    public static String updateLeadWithStatus(Id leadId, String status, DateTime scheduleDate, String rating, String othercom, String openreason,String alloctreason) {
        String returnmessage='';
        Lead leadRecord = [SELECT Id, Status,RecordTypeId, RecordType.Name, Rating,Lead_Status__c, Unqualified_Reason__c,Last_Unqualified_At__c,Remark__c,OwnerId,
                           Last_Unqualified_by__c,Mark_Unqualified__c,No_Of_Times_Unqualified__c,Lead_Assigned__c FROM Lead WHERE Id = :leadId LIMIT 1];
        system.debug(rating);
        List<Lead_Unqualification__c> lqlst = new List<Lead_Unqualification__c>();
        
        try{
            
            if (status == 'RNR' || status == 'Pre Sales Follow Up'|| status == 'Sales Follow up') {
                insert new Follow_Up__c(
                    SLead__c = leadId,
                    Scheduled_Date__c = scheduleDate,
                    Subject__c = 'Follow up for ' + othercom
                );
            }
            
            if (status == 'Site Visit Schedule') {
                system.debug('Inside');
                insert new Site_Visit__c(
                    SLead__c = leadId,
                    Date__c = scheduleDate,
                    Status__c = 'Scheduled'
                );
            }
            
            user u = [SELECT Id,Name,Profile.Name FROM user WHERE Id=:userinfo.getUserId()];
            
            leadRecord.Lead_Status__c = status;
            //leadRecord.Closed_Lost_Reason__c=rating;
            if(status == 'Request For Rejection' && leadRecord.RecordType.Name=='Pre Sales' && leadRecord.No_Of_Times_Unqualified__c < 3){
                markleadUnqualified = true;
                leadRecord.Last_Unqualified_At__c = system.now();
                leadRecord.Last_Unqualified_by__c = UserInfo.getUserId();
                leadRecord.Mark_Unqualified__c = true;
                leadRecord.No_Of_Times_Unqualified__c += 1;
                leadRecord.Lead_Assigned__c = false;
                leadRecord.Lead_status__c = 'New';
                leadRecord.Reason_For_Rejection__c=rating;
                leadRecord.Reasons_in_Detail__c=othercom;
                
                Lead_Unqualification__c lq = new Lead_Unqualification__c();
                lq.User__c = UserInfo.getUserId();
                if (rating == 'Other') {
                    lq.Unqualified_Reason__c = rating +' : '+othercom;
                }
                else{
                    lq.Unqualified_Reason__c = rating;
                }
                lq.Unqualified_At__c = system.now();
                lq.Lead__c =leadRecord.Id;
                lq.Type__c='Pre Sales';
                lqlst.add(lq);
            }
            else if(status == 'Request For Rejection' && leadRecord.RecordType.Name=='Sales'){
                User ur= [select id,ManagerId from User where Id =:leadRecord.OwnerId];
                leadRecord.OwnerId=ur.ManagerId;
                leadRecord.Closed_Lost_Reason__c=rating;
                leadRecord.Reasons_in_Detail__c=othercom;
                
                Lead_Unqualification__c lq = new Lead_Unqualification__c();
                lq.User__c = UserInfo.getUserId();
                lq.Unqualified_Reason__c = rating +' : '+othercom;
                lq.Unqualified_At__c = system.now();
                lq.Lead__c =leadRecord.Id;
                lq.Type__c='Sales';
                lqlst.add(lq);
            }
            if(status == 'Unqualified'){
                leadRecord.Unqualified_Reason__c=rating;
            }
            if(status == 'Rejected'){
                leadRecord.Reason_For_Rejection__c=rating;
            }
            if(status == 'Closed Lost'){
                leadRecord.Closed_Lost_Reason__c=rating;
            }
            if(status == 'Open'){
                leadRecord.Open_Reason__c=openreason;
            }
            if(status == 'Allocated'){
                leadRecord.Allocated_Reason__c=alloctreason;
            }
            if(lqlst.size()>0){
                insert lqlst;
            }
            
            update leadRecord;
            returnmessage= 'Updated Successully';
        }
        catch (Exception e) {
            System.debug('An error occurred: ' + e.getMessage());
            for (Integer i = 0; i < e.getNumDml(); i++) {
                // Get the error message for the current error
                String errorMessage = e.getDmlMessage(i);
                // You can log or handle the error message as needed
                System.debug('An error occurred: ' + errorMessage);
                returnmessage= errorMessage;
                return returnmessage;
            }
        }
        return returnmessage;
    }
    @AuraEnabled
    public static List<String> getUnqualifiedReasons() {
        List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult = Lead.Unqualified_Reason__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
        
        for (Schema.PicklistEntry entry : picklistValues) {
            options.add(entry.getLabel());
        }
        return options;
    }
    
    @AuraEnabled
    public static List<String> getClosedLostReason() {
        List<String> stages = new List<String>();
        Schema.DescribeFieldResult fieldDescribe = Lead.Reason_For_Rejection__c.getDescribe();
        for (Schema.PicklistEntry entry : fieldDescribe.getPicklistValues()) {
            stages.add(entry.getLabel());
            
        }
        system.debug('stages '+stages);
        return stages;
    }
    
    @AuraEnabled
    public static List<String> getOpenReason() {
        List<String> stages = new List<String>();
        Schema.DescribeFieldResult fieldDescribe = Lead.Open_Reason__c.getDescribe();
        for (Schema.PicklistEntry entry : fieldDescribe.getPicklistValues()) {
            stages.add(entry.getLabel());
        }
        system.debug('stages '+stages);
        return stages;
    }
    
    @AuraEnabled
    public static List<String> getAllocatedReason() {
        List<String> stages = new List<String>();
        Schema.DescribeFieldResult fieldDescribe = Lead.Allocated_Reason__c.getDescribe();
        for (Schema.PicklistEntry entry : fieldDescribe.getPicklistValues()) {
            stages.add(entry.getLabel());
        }
        system.debug('stages '+stages);
        return stages;
    }
}