force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/Amount1__c.field-meta.xml
<CustomField>
    <fullName>Amount1__c</fullName>
    <formula>/* Payment_percent__c * Quote__r.Total_Consideration_with_taxes_and_other__c*/
Payment_percent__c *  Quote__r.GRAND_TOTAL__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Payment schedules</relationshipLabel>
    <relationshipName>Payment_schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{0000}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/getQuoteData.cls
public class getQuoteData {
    public Quote__c qout{get;set;}
    public id recid{get;set;}
    
	    public decimal totalPercent {get;set;}
     public decimal totalAmount {get;set;}
     Public getQuoteData(ApexPages.StandardController controller){
           this.recId = ApexPages.currentPage().getParameters().get('id');
      
     //  string recordId = controller.getId();
       Quote__c qt = [select Id from Quote__c where Id=:recId limit 1];  
       AggregateResult agg = [select sum(Payment_percent__c) perc, sum(Amount1__c) amt,Quote__c from Payment_Schedule__c where Quote__c=:recId GROUP BY Quote__c LIMIT 1];
         totalPercent = (Decimal) agg.get('perc');
         totalAmount = (Decimal) agg.get('amt');
         
         qout =[select Id,(select id ,Name,Payment_percent__c,Amount1__c,S_No__c from Payment_Schedules__r order by S_No__c asc) from Quote__c where Id=:recId limit 1];
    }

}