force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SiteVisit-{0000}</displayFormat>
        <label>Site Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Revisit_Count__c.field-meta.xml
<CustomField>
    <fullName>Revisit_Count__c</fullName>
    <label>Revisit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Verified by GRE</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Not Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReVisitController.cls
public class ReVisitController {
    @AuraEnabled
    public static void updateLastNote(String SVId, String newNote, DateTime RSVDate) {
        Datetime dt = Datetime.now();
        Timezone tz = Timezone.getTimeZone('Asia/Kolkata');
        String strTimeInAMorPM = RSVDate.format('MMMMM dd, yyyy hh:mm:ss a');
        
        Integer noteCount = 1;
        Site_Visit__c SVRecord = [SELECT Id, Revisit_Count__c,Revisit_Details__c,Reschedule_Date__c,Status__c,Reschedule_Reason__c FROM Site_Visit__c WHERE Id =:SVId LIMIT 1];
        User us = [select id,name from User where id =: userInfo.getUserId()];

        if (SVRecord.Revisit_Details__c == null) {
            SVRecord.Revisit_Details__c = '';
        }
        else if (!SVRecord.Revisit_Details__c.trim().equals('')) {
            List<String> notes = SVRecord.Revisit_Details__c.split('\n');
            noteCount = notes.size() + 1;
        }
        SVRecord.Revisit_Details__c += '\nRe-Visit ' + noteCount + ': (' + strTimeInAMorPM + ') :      ' + newNote;
        SVRecord.Reschedule_Date__c=RSVDate;
        SVRecord.Reschedule_Reason__c=newNote;
        SVRecord.Status__c='Rescheduled';
        SVRecord.Revisit_Count__c+=1;
        update SVRecord;
    }

}