force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SiteVisit-{0000}</displayFormat>
        <label>Site Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Lead_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Name__c</fullName>
    <formula>SLead__r.FirstName +&apos; &apos;+  SLead__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Lead_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Lead_Phone_Number__c</fullName>
    <formula>SLead__r.Phone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Phone Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/OTP__c.field-meta.xml
<CustomField>
    <fullName>OTP__c</fullName>
    <label>OTP</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WhatsAppTriggerHandler.cls
public class WhatsAppTriggerHandler {

    public static void processNewLeads(List<Lead> leadList) {
        List<Lead> leadsToSend = new List<Lead>();
        List<Lead> leadsToUpdateOTP = new List<Lead>();
String otp;
        for (Lead l : leadList) {
            if (String.isNotBlank(l.Phone__C)) {
                leadsToSend.add(l);
                otp = GenerateOTP.generateUniqueOTP();
                 Lead updatedLead = new Lead(
                            Id = l.Id,
                            OTP__c = otp
                        );
                        update updatedLead;
             //   l.OTP__c = GenerateOTP.generateUniqueOTP();
                
                // leadsToUpdateOTP.add(l);
                
            }
        }
        
           if (!leadsToUpdateOTP.isEmpty()) {
           
            // Enqueue SMS queueables for each lead
            for (Lead l : leadsToUpdateOTP) {
                String name = ((l.FirstName != null) ? l.FirstName : '') + ' ' + ((l.LastName != null) ? l.LastName : '');
                System.enqueueJob(new SendSMSQueueable(l.Phone__c, name.trim(), otp));
            }
        }


        if (!leadsToSend.isEmpty()) {
             System.enqueueJob(new WhatsAppBulkSender(leadsToSend));
        }
    }
    public static void processSitevisit(List<Site_Visit__c> lstsv){
         for (Site_Visit__c sv : lstsv) {
             String otp = sv.OTP__c;
             String leadName= sv.Lead_Name__c;
             String phone = sv.Lead_Phone_Number__c;
              //  String name = ((l.FirstName != null) ? l.FirstName : '') + ' ' + ((l.LastName != null) ? l.LastName : '');
                System.enqueueJob(new SendSMSQueueable(phone, leadName, otp));
            }
    }
}