force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SiteVisit-{0000}</displayFormat>
        <label>Site Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/OTP__c.field-meta.xml
<CustomField>
    <fullName>OTP__c</fullName>
    <label>OTP</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/SLead__c.field-meta.xml
<CustomField>
    <fullName>SLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SiteVisitControllerTest.cls
@isTest
public class SiteVisitControllerTest {
@isTest
    public static void testmethodst(){
        Lead ld = new Lead(
            LastName = 'Test Lead 1',
            Company = 'Company A'
        );
        insert ld;
        List<Site_Visit__c> sv = New List<Site_Visit__c>();
        
          Site_Visit__c sv1 = new Site_Visit__c(
            Slead__c = ld.Id,
            OTP__c = '0000'
        );
        insert sv1;
        sv.add(sv1);
        SiteVisitController.checkSiteVisitForRoundRobin(sv);

    }
}