force-app/main/default/objects/Related_Source__c/Related_Source__c.object-meta.xml
<CustomObject>
    <label>Related Source</label>
    <nameField>
        <displayFormat>RS-{000}</displayFormat>
        <label>Related Source</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Sources</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Source__c/fields/Lead_status1__c.field-meta.xml
<CustomField>
    <fullName>Lead_status1__c</fullName>
    <label>Lead status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>RNR</fullName>
            </value>
            <value>
                <fullName>Pre Sales Follow Up</fullName>
            </value>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Site Visit Schedule</fullName>
            </value>
            <value>
                <fullName>New sales enquiry</fullName>
            </value>
            <value>
                <fullName>Sales Follow up</fullName>
            </value>
            <value>
                <fullName>SV Completed</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Request for Rejection</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Related_Source__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <formula>TEXT(SLead__r.Lead_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Source__c/fields/SLead__c.field-meta.xml
<CustomField>
    <fullName>SLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Related Sources</relationshipLabel>
    <relationshipName>Related_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RelatedSourceLockUnlockBatch.cls
public class RelatedSourceLockUnlockBatch implements Database.Batchable<sObject>, Database.Stateful {
    
 
    
  
 
    public RelatedSourceLockUnlockBatch() {
        
    }
  
    
    /**
     * Start method - Query all Leads
     */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'select Id,Name,SLead__r.OwnerId,SLead__r.Lead_Status__c,SLead__r.Allocated_Project__c from related_source__c where SLead__c != null';
                     
        integer i=0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        return Database.getQueryLocator(query);
    }
    
    /**
     * Execute method - Process each batch of Leads
     */
    public void execute(Database.BatchableContext bc, List<related_source__c> leads) {
        
        // Collect Lead IDs
        List<related_source__c> reList = new List<related_source__c>();
        for(related_source__c ld : leads) {
            ld.OwnerId = ld.SLead__r.OwnerId;
            ld.Lead_status1__c = ld.SLead__r.Lead_Status__c;
            ld.Allocated_Project__c = ld.SLead__r.Allocated_Project__c;
            reList.add(ld);
        }
        
        update reList;
       
    }
    
    
    public void finish(Database.BatchableContext bc) {
       
    }
}