force-app/main/default/objects/Block__c/Block__c.object-meta.xml
<CustomObject>
    <label>Block</label>
    <nameField>
        <label>Block Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blocks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Employeed_at__c.field-meta.xml
<CustomField>
    <fullName>Employeed_at__c</fullName>
    <label>Employeed at</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Notes_and_Comments__c.field-meta.xml
<CustomField>
    <fullName>Notes_and_Comments__c</fullName>
    <label>Notes and Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/PAN_Number__c.field-meta.xml
<CustomField>
    <fullName>PAN_Number__c</fullName>
    <label>PAN Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Plot__c.field-meta.xml
<CustomField>
    <fullName>Plot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Plot__c.Project__r.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>Plot__c.Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Plot__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Profession__c.field-meta.xml
<CustomField>
    <fullName>Profession__c</fullName>
    <label>Profession</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Residential_Status__c.field-meta.xml
<CustomField>
    <fullName>Residential_Status__c</fullName>
    <label>Residential Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resident</fullName>
            </value>
            <value>
                <fullName>Non-Resident</fullName>
            </value>
            <value>
                <fullName>Foreign National Of Indian Origin</fullName>
                <isActive>false</isActive>
                <label>Foreign National Of Indian Origin</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/SLead__c.field-meta.xml
<CustomField>
    <fullName>SLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/Co_Applicant__c.object-meta.xml
<CustomObject>
    <label>Co Applicant</label>
    <nameField>
        <label>Co Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Co Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Co_Applicant__c/fields/Anniverssary_Date__c.field-meta.xml
<CustomField>
    <fullName>Anniverssary_Date__c</fullName>
    <label>Anniversary Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Co Applicants</relationshipLabel>
    <relationshipName>Co_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Employeed_at__c.field-meta.xml
<CustomField>
    <fullName>Employeed_at__c</fullName>
    <label>Employeed at</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/PAN_Number__c.field-meta.xml
<CustomField>
    <fullName>PAN_Number__c</fullName>
    <label>PAN Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Passport_Number__c.field-meta.xml
<CustomField>
    <fullName>Passport_Number__c</fullName>
    <label>Passport Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Profession__c.field-meta.xml
<CustomField>
    <fullName>Profession__c</fullName>
    <label>Profession</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Residential_Status__c.field-meta.xml
<CustomField>
    <fullName>Residential_Status__c</fullName>
    <label>Residential Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resident</fullName>
            </value>
            <value>
                <fullName>Non-Resident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Shri</fullName>
                <isActive>false</isActive>
                <label>Shri</label>
            </value>
            <value>
                <fullName>Smt</fullName>
                <isActive>false</isActive>
                <label>Smt</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Son_Daughter_Wife_of__c.field-meta.xml
<CustomField>
    <fullName>Son_Daughter_Wife_of__c</fullName>
    <label>Son/Daughter/Wife of</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plot__c/Plot__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot__c/fields/Block_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Block_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Block</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Block__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Block__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/BookingPDFController.cls
public class BookingPDFController {
    public Booking__c booking { get; set; }
    public Co_Applicant__c firstCoApplicant { get; set; }
    public List<String> textLines { get; set; }

    public BookingPDFController(ApexPages.StandardController controller) {
        Id bookingId = controller.getId();
        booking = [SELECT Id, Notes_and_Comments__c, Plot__r.Name, Plot__r.Block_Lookup__r.Name FROM Booking__c WHERE Id = :bookingId];
        system.debug(booking);
        
        if(booking.Notes_and_Comments__c != Null) {
            textLines = booking.Notes_and_Comments__c.split('\r\n');
        } else {
            textLines = new List<String>();
        }

         
        
        List<Co_Applicant__c> coApplicants = [
            SELECT Name, Salutation__c,Date_of_Birth__c,Anniverssary_Date__c,Son_Daughter_Wife_of__c,Nationality__c,	Passport_Number__c,	PAN_Number__c,Email__c,Primary_Phone__c,Residential_Status__c,	Profession__c,	Industry__c,Employeed_at__c,Designation__c
            FROM Co_Applicant__c 
            WHERE Booking__c = :bookingId 
            ORDER BY CreatedDate ASC 
            LIMIT 1
        ];

        if (!coApplicants.isEmpty()) {
            firstCoApplicant = coApplicants[0];
        }
    }
     @AuraEnabled
    public static string sendEmailtoCustomer(String recId)
    {
        Booking__c bk = [SELECT Id, Project__c,Email__c  FROM Booking__c WHERE Id=:recId];
    //    if(qt.Quote_status__c == 'Approved' || qt.Quote_status__c == 'Drafted'){
            Messaging.SingleEmailMessage semail = new Messaging.SingleEmailMessage();
            Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
           
   
            PageReference pref;
            pref=page.BookingFormZGC;
            pref.getParameters().put('id',recId);
            pref.setRedirect(true);
            system.debug(pref);
            Blob b;
            
          Boolean isTest = System.Test.isRunningTest();
           if(isTest){
                b = blob.valueOf('Unit.Test');
            }else{
                b = pref.getContent();
            }
            attach.setFileName('Zuari_BookingForm.pdf');
            attach.setBody(b);
            semail.setSubject('Zuari Booking Form');
            
            List<string> sendTo = new List<string>();
            if(bk.Email__c !=null){
                sendTo.add(bk.Email__c);
            }
            
           // if(bk.SLead__r.Secondary_Email__c !=null){
              //  sendTo.add(bk.SLead__r.Secondary_Email__c);
           // }
            system.debug(sendTo);
            semail.setToAddresses(sendTo);
            semail.setHtmlBody('Dear Sir/Madam,<br/> <br/> Thank you very much for your interest in '+bk.Project__c +'.<br/></br>Please find the attached booking form.<br/><b>Note</b>: This is a sample booking from purely for reference.<br/></br>Please feel free to talk us for clarification if any.<br/><br/>Best Regards<br/>Mantri');
            semail.setFileAttachments(new Messaging.EmailFileAttachment[]{attach});
        	system.debug(semail);
            if(sendTo.size()>0){
                try{
                Messaging.sendEmail(new Messaging.SingleEmailMessage[]{semail});
                system.debug(semail);
                 
                }
                
                catch(Exception e){
                    System.debug('Error sending email: ' + e.getMessage());
                }
                
            return 'Booking form sent to customer';    
               
            }else{
                return 'Please enter email address';
            }
     
    }
    
    
    
    
}