force-app/main/default/objects/Block__c/Block__c.object-meta.xml
<CustomObject>
    <label>Block</label>
    <nameField>
        <label>Block Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blocks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot__c/Plot__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot__c/fields/BHK_Type__c.field-meta.xml
<CustomField>
    <fullName>BHK_Type__c</fullName>
    <label>BHK Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1BHK</fullName>
            </value>
            <value>
                <fullName>2BHK</fullName>
            </value>
            <value>
                <fullName>3BHK</fullName>
            </value>
            <value>
                <fullName>4BHK</fullName>
            </value>
            <value>
                <fullName>5BHK</fullName>
            </value>
            <value>
                <fullName>2BHK+ 2T</fullName>
                <isActive>false</isActive>
                <label>2BHK+ 2T</label>
            </value>
            <value>
                <fullName>3BHK+ 2T</fullName>
                <isActive>false</isActive>
                <label>3BHK+ 2T</label>
            </value>
            <value>
                <fullName>3BHK+ 3T</fullName>
                <isActive>false</isActive>
                <label>3BHK+ 3T</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Block__c.field-meta.xml
<CustomField>
    <fullName>Block__c</fullName>
    <label>Block</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>A4</fullName>
            </value>
            <value>
                <fullName>A6</fullName>
            </value>
            <value>
                <fullName>A7</fullName>
            </value>
            <value>
                <fullName>A8</fullName>
            </value>
            <value>
                <fullName>A9</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>B3</fullName>
            </value>
            <value>
                <fullName>B5</fullName>
            </value>
            <value>
                <fullName>B6</fullName>
            </value>
            <value>
                <fullName>B7</fullName>
            </value>
            <value>
                <fullName>B8</fullName>
            </value>
            <value>
                <fullName>B9</fullName>
            </value>
            <value>
                <fullName>B10</fullName>
            </value>
            <value>
                <fullName>B11</fullName>
            </value>
            <value>
                <fullName>B13</fullName>
            </value>
            <value>
                <fullName>B17</fullName>
            </value>
            <value>
                <fullName>B18</fullName>
            </value>
            <value>
                <fullName>B19</fullName>
            </value>
            <value>
                <fullName>B20</fullName>
            </value>
            <value>
                <fullName>B21</fullName>
            </value>
            <value>
                <fullName>B23</fullName>
            </value>
            <value>
                <fullName>B27</fullName>
            </value>
            <value>
                <fullName>B28</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C8</fullName>
            </value>
            <value>
                <fullName>C9</fullName>
            </value>
            <value>
                <fullName>C10</fullName>
            </value>
            <value>
                <fullName>C12</fullName>
            </value>
            <value>
                <fullName>C13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Block_Name__c.field-meta.xml
<CustomField>
    <fullName>Block_Name__c</fullName>
    <formula>Block_Lookup__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Block Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Plot_Type__c.field-meta.xml
<CustomField>
    <fullName>Plot_Type__c</fullName>
    <label>Plot Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intermediate Site</fullName>
            </value>
            <value>
                <fullName>Corner Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Rate_per_sqft__c.field-meta.xml
<CustomField>
    <fullName>Rate_per_sqft__c</fullName>
    <label>Rate / Sq.ft on SBA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>to capture the availability of the plot</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>BLOCKED</fullName>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Super_Built_up_Area__c.field-meta.xml
<CustomField>
    <fullName>Super_Built_up_Area__c</fullName>
    <label>Super Built up Area(Sq.ft)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Unit_Facing_Direction__c.field-meta.xml
<CustomField>
    <fullName>Unit_Facing_Direction__c</fullName>
    <label>Unit Facing Direction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EAST</fullName>
            </value>
            <value>
                <fullName>WEST</fullName>
            </value>
            <value>
                <fullName>SOUTH</fullName>
            </value>
            <value>
                <fullName>NORTH</fullName>
            </value>
            <value>
                <fullName>North East</fullName>
            </value>
            <value>
                <fullName>North West</fullName>
            </value>
            <value>
                <fullName>South West</fullName>
            </value>
            <value>
                <fullName>WEST/NORTH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Wing__c.field-meta.xml
<CustomField>
    <fullName>Wing__c</fullName>
    <label>Wing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wing A</fullName>
            </value>
            <value>
                <fullName>Wing B</fullName>
            </value>
            <value>
                <fullName>Wing C</fullName>
            </value>
            <value>
                <fullName>Wing D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Available_Units__c.field-meta.xml
<CustomField>
    <fullName>Available_Units__c</fullName>
    <label>Vacant Units</label>
    <summaryFilterItems>
        <field>Plot__c.Status__c</field>
        <operation>equals</operation>
        <value>Available, Vacant</value>
    </summaryFilterItems>
    <summaryForeignKey>Plot__c.Project__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/BHK_Type__c.field-meta.xml
<CustomField>
    <fullName>BHK_Type__c</fullName>
    <label>BHK Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK</fullName>
            </value>
            <value>
                <fullName>2.5 BHK</fullName>
            </value>
            <value>
                <fullName>3 BHK</fullName>
            </value>
            <value>
                <fullName>3.5 BHK</fullName>
            </value>
            <value>
                <fullName>4 BHK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Blocked_Units__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Units__c</fullName>
    <label>Blocked Units</label>
    <summaryFilterItems>
        <field>Plot__c.Status__c</field>
        <operation>equals</operation>
        <value>Blocked</value>
    </summaryFilterItems>
    <summaryForeignKey>Plot__c.Project__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Not_Released_Units__c.field-meta.xml
<CustomField>
    <fullName>Not_Released_Units__c</fullName>
    <label>Not Released Units</label>
    <summaryFilterItems>
        <field>Plot__c.Status__c</field>
        <operation>equals</operation>
        <value>NFS</value>
    </summaryFilterItems>
    <summaryForeignKey>Plot__c.Project__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Sold_Units__c.field-meta.xml
<CustomField>
    <fullName>Sold_Units__c</fullName>
    <label>Sold Units</label>
    <summaryFilterItems>
        <field>Plot__c.Status__c</field>
        <operation>equals</operation>
        <value>Sold</value>
    </summaryFilterItems>
    <summaryForeignKey>Plot__c.Project__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Units__c.field-meta.xml
<CustomField>
    <fullName>Total_Units__c</fullName>
    <label>Total Units</label>
    <summaryForeignKey>Plot__c.Project__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/newProjectBoardControllerClass.cls
/****************************************************************
* Class Name : newProjectBoardControllerClass
* Company : Fingertipplus
* Created Date : 1-04-2025
* @description : This class is responsible for showing the data in Custom Tab Inventory Managment.
* @author : Praveen Kumar
* Used By : newInventoryManagment Aura Component
* 
*
* Change Log:
* -----------------------------------------------------------------------------
* Ver | Author | Date | Description
* -----------------------------------------------------------------------------
* 1.0 | Praveen Kumar | 1-04-2025 | Initial version
* -----------------------------------------------------------------------------
**************************************************************/
public class newProjectBoardControllerClass {
     @auraEnabled
    Public static List<Project__c> getProjects(){
        return [SELECT Id,Name,Project__c,Project_Address__c,Total_Units__c,Available_Units__c,Booked_Units__c,Not_Released_Units__c,Blocked_Units__c, Sold_Units__c FROM Project__c];
    }
    @auraEnabled
    Public static List<Plot__c> getPlots(string Project){
        return [SELECT Id,Name,Project__c, BHK_Type__c,  Unit_Facing_Direction__c, Plot_Type__c, Status__c,Super_Built_up_Area__c,Rate_per_sqft__c,
                Block_Name__c,Wing__c FROM Plot__c WHERE Project__c=:project order by Name Asc];
    }
 @AuraEnabled
    public static List<Map<String, String>> getPicklistValues(String objectName, String fieldName) {
        List<Map<String, String>> picklistValues = new List<Map<String, String>>();
        
        // Get the describe result for the object
        Schema.DescribeSObjectResult objectDescribe = Schema.getGlobalDescribe().get(objectName).getDescribe();
        
        // Get the field describe result
        Schema.DescribeFieldResult fieldDescribe = objectDescribe.fields.getMap().get(fieldName).getDescribe();
        
        // Get the picklist values
        for (Schema.PicklistEntry entry : fieldDescribe.getPicklistValues()) {
            if (entry.isActive()) { // Only include active values
                picklistValues.add(new Map<String, String>{
                    'label' => entry.getLabel(),
                    'value' => entry.getValue()
                });
            }
        }
        
        return picklistValues;
    }
	
     @AuraEnabled(cacheable=true)
    public static List<String> getBlockNames(String projectId) {
        List<Block__c> blocks = [SELECT Name FROM Block__c WHERE Project__c = :projectId];
        List<String> blockNames = new List<String>();
        for (Block__c block : blocks) {
            blockNames.add(block.Name);
        }
        return blockNames;
    }
}