force-app/main/default/objects/Block__c/Block__c.object-meta.xml
<CustomObject>
    <label>Block</label>
    <nameField>
        <label>Block Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blocks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot__c/Plot__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot__c/fields/BHK_Type__c.field-meta.xml
<CustomField>
    <fullName>BHK_Type__c</fullName>
    <label>BHK Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1BHK</fullName>
            </value>
            <value>
                <fullName>2BHK</fullName>
            </value>
            <value>
                <fullName>3BHK</fullName>
            </value>
            <value>
                <fullName>4BHK</fullName>
            </value>
            <value>
                <fullName>5BHK</fullName>
            </value>
            <value>
                <fullName>2BHK+ 2T</fullName>
                <isActive>false</isActive>
                <label>2BHK+ 2T</label>
            </value>
            <value>
                <fullName>3BHK+ 2T</fullName>
                <isActive>false</isActive>
                <label>3BHK+ 2T</label>
            </value>
            <value>
                <fullName>3BHK+ 3T</fullName>
                <isActive>false</isActive>
                <label>3BHK+ 3T</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Block__c.field-meta.xml
<CustomField>
    <fullName>Block__c</fullName>
    <label>Block</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>A4</fullName>
            </value>
            <value>
                <fullName>A6</fullName>
            </value>
            <value>
                <fullName>A7</fullName>
            </value>
            <value>
                <fullName>A8</fullName>
            </value>
            <value>
                <fullName>A9</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>B3</fullName>
            </value>
            <value>
                <fullName>B5</fullName>
            </value>
            <value>
                <fullName>B6</fullName>
            </value>
            <value>
                <fullName>B7</fullName>
            </value>
            <value>
                <fullName>B8</fullName>
            </value>
            <value>
                <fullName>B9</fullName>
            </value>
            <value>
                <fullName>B10</fullName>
            </value>
            <value>
                <fullName>B11</fullName>
            </value>
            <value>
                <fullName>B13</fullName>
            </value>
            <value>
                <fullName>B17</fullName>
            </value>
            <value>
                <fullName>B18</fullName>
            </value>
            <value>
                <fullName>B19</fullName>
            </value>
            <value>
                <fullName>B20</fullName>
            </value>
            <value>
                <fullName>B21</fullName>
            </value>
            <value>
                <fullName>B23</fullName>
            </value>
            <value>
                <fullName>B27</fullName>
            </value>
            <value>
                <fullName>B28</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C8</fullName>
            </value>
            <value>
                <fullName>C9</fullName>
            </value>
            <value>
                <fullName>C10</fullName>
            </value>
            <value>
                <fullName>C12</fullName>
            </value>
            <value>
                <fullName>C13</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Block_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Block_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Block</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Block__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Block__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Built_up_area__c.field-meta.xml
<CustomField>
    <fullName>Built_up_area__c</fullName>
    <label>Built up area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Carpet_Area__c</fullName>
    <label>Carpet Area(Sq.ft)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Floor_Rise__c.field-meta.xml
<CustomField>
    <fullName>Floor_Rise__c</fullName>
    <label>Floor Rise Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/GST1__c.field-meta.xml
<CustomField>
    <fullName>GST1__c</fullName>
    <label>GST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Premium_Charge__c.field-meta.xml
<CustomField>
    <fullName>Premium_Charge__c</fullName>
    <formula>IF(
    TEXT(Unit_Facing_Direction__c) = &apos;East&apos; &amp;&amp; ISBLANK(TEXT(Corner__c)),
    0.05,
    IF(
        TEXT(Corner__c) = &apos;Corner&apos;,
        0.10,
        IF(
            OR(
                TEXT(Corner__c) = &apos;Premium&apos;,
                TEXT(Corner__c) = &apos;Ultra Premium&apos;
            ),
            0.125,
            0
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Premium Charge</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>to capture the availability of the plot</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>BLOCKED</fullName>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Super_Built_up_Area__c.field-meta.xml
<CustomField>
    <fullName>Super_Built_up_Area__c</fullName>
    <label>Super Built up Area(Sq.ft)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/UDS__c.field-meta.xml
<CustomField>
    <fullName>UDS__c</fullName>
    <label>UDS</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/BHK_Type__c.field-meta.xml
<CustomField>
    <fullName>BHK_Type__c</fullName>
    <label>BHK Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK</fullName>
            </value>
            <value>
                <fullName>2.5 BHK</fullName>
            </value>
            <value>
                <fullName>3 BHK</fullName>
            </value>
            <value>
                <fullName>3.5 BHK</fullName>
            </value>
            <value>
                <fullName>4 BHK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Facing__c.field-meta.xml
<CustomField>
    <fullName>Facing__c</fullName>
    <label>Facing</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EAST</fullName>
            </value>
            <value>
                <fullName>WEST</fullName>
            </value>
            <value>
                <fullName>NORTH</fullName>
            </value>
            <value>
                <fullName>SOUTH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apartments</fullName>
            </value>
            <value>
                <fullName>Villas</fullName>
            </value>
            <value>
                <fullName>Plots</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/newProjectBoardControllerClassTest.cls
@isTest
public class newProjectBoardControllerClassTest {
    
    @TestSetup
    static void setup() {
        Project__c pr1 = new  Project__c();
        pr1.Name = 'Zuari Garden City';
      //  pr1.Project_Type__c='Apartments';
        insert pr1;
        
        Block__c blk = new Block__c();
        blk.Name='A';
        blk.Project__c=pr1.id;
        insert blk;
        
        Plot__c pl = new Plot__c();
        pl.Name = '101';
       
        // Pick a valid Status__c value dynamically
		List<Schema.PicklistEntry> statusValues = Plot__c.Status__c.getDescribe().getPicklistValues();
		pl.Status__c = statusValues[0].getValue();
        
        pl.Project__c = pr1.Id;
        pl.Block__c = 'A4';
        pl.Block_Lookup__c = blk.Id;
        pl.Carpet_Area__c = 850;
       // pl.Balcony_Sq_mts__c = 20;
       // pl.Balcony_Area__c = 100;
      //  pl.BHK_Type__c = '3 BHK + 2T';
      //  pl.Premium_Status__c = 'Premium';
        pl.Floor__c = '1';
      //  pl.Share__c = 'MHPL';
       // pl.Facing__c = 'EAST';
       // pl.Carpet_Sq_mts__c = 80;
       // pl.CA__c = 75;
        pl.Built_up_area__c = 1200;
        pl.UDS__c = 300;
      //  pl.UDS_Sq_mts__c = 50;
        pl.Super_built_up_area__c = 1500;
      //  pl.Price_Per_Sq_Ft__c = 5000;
        pl.Floor_Rise__c = 200;
        //pl.Premium_Charge__c = 100000;
       // pl.Covered_Park_Parking__c = 50000;
        pl.Other_Charges__c = 20000;
       // pl.Solar_Charges__c = 15000;
        pl.GST1__c = 18;
        
        insert pl;
        
        
    }
     @IsTest
    static void projectBoardControllerClassTest() {
        id projectId = [Select id from project__c limit 1].id;
        Test.startTest();
        newProjectBoardControllerClass.getProjects();
        newProjectBoardControllerClass.getPlots(projectId);
        newProjectBoardControllerClass.getPicklistValues('Plot__c','Status__c');
        newProjectBoardControllerClass.getBlockNames(projectId);
        Test.stopTest();
    }

}